apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cga-proxy.envoy.fullname" . }}
  labels:
    {{- include "cga-proxy.labels" . | nindent 4 }}
    {{- include "cga-proxy.envoy.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  replicas: {{ .Values.envoy.replicaCount }}
  selector:
    matchLabels:
      {{- include "cga-proxy.selectorLabels" . | nindent 6 }}
      {{- include "cga-proxy.envoy.labels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.commonPodAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.envoy.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "cga-proxy.selectorLabels" . | nindent 8 }}
        {{- include "cga-proxy.envoy.labels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.envoy.podSecurityContext | nindent 8 }}
      priorityClassName: {{ .Values.priorityClassName }}
      containers:
        - name: envoy
          securityContext:
            {{- toYaml .Values.envoy.securityContext | nindent 12 }}
          image: {{ include "cga-proxy.envoy.imageConcat" . }}
          imagePullPolicy: {{ .Values.envoy.image.pullPolicy }}
          env:
            {{- with .Values.envoy.customEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: FYDE_PROXY_HOST
              value: {{ include "cga-proxy.orchestrator.fullname" . }}
            - name: FYDE_PROXY_PORT
              value: {{ .Values.orchestrator.service.port.grpc  | quote }}
          ports:
            - name: listener
              containerPort: {{ .Values.envoy.service.port.listener }}
              protocol: TCP
            {{- if .Values.serviceMonitor }}
            - name: metrics
              containerPort: {{ .Values.envoy.service.port.metrics  }}
              protocol: TCP
            {{- end }}
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: listener
          resources:
            {{- toYaml .Values.envoy.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.envoy.nodeSelector | nindent 8 }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                {{- include "cga-proxy.envoy.labels" . | nindent 16 }}
            topologyKey: kubernetes.io/hostname
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "cga-proxy.envoy.labels" . | nindent 20 }}
                topologyKey: failure-domain.beta.kubernetes.io/zone
      tolerations:
        {{- toYaml .Values.envoy.tolerations | nindent 8 }}
