{{- if gt (int .Values.envoy.replicaCount) 1 -}}
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cga-proxy.envoy.fullname" . }}
  labels:
    {{- include "cga-proxy.labels" . | nindent 4 }}
    {{- include "cga-proxy.envoy.labels" . | nindent 4 }}
spec:
  minAvailable: {{ div (mul .Values.envoy.replicaCount 2) 3 }}
  selector:
    matchLabels:
      {{- include "cga-proxy.selectorLabels" . | nindent 6 }}
      {{- include "cga-proxy.envoy.labels" . | nindent 6 }}
{{- end -}}
