# Default values for cga-directory-connector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Provide a name in place of cga-directory-connector for labels
nameOverride: ""

# -- Provide a name to substitute for the full names of resources
fullnameOverride: ""

# -- Provide pod annotations that all pods will use
commonPodAnnotations: {}

# -- Create cronjob
cronjob:
  enabled: false
  schedule: "*/30 * * * *"
  suspended: false

# -- Create service monitor resources
serviceMonitor: false

# -- Set revision history limit
revisionHistoryLimit: 10

# -- Set priorityClassName
priorityClassName: ""

# Specify existingSecret values or set newSecret value
# existingSecret has higher priority when defined
# More information for enrollment and auth token
# <https://campus.barracuda.com/product/cloudgenaccess/doc/93201549/user-directory-connector>
enrollmentToken:
  existingSecret:
    # -- Existing secret resource name
    name: ""
    # -- Existing secret key
    key: ""
  newSecret:
    # -- Enrollment token value to be created with new secret
    value: ""

authToken:
  # -- Available directory types: azure/google/okta
  type: ""
  existingSecret:
    # -- Existing secret resource name
    name: ""
    # -- Existing secret key
    key: ""
  newSecret:
    # -- Enrollment token value to be created with new secret
    value: ""

image:
  # -- Docker image to use
  repository: fydeinc/fyde-connector
  # -- Docker image pullPolicy
  pullPolicy: IfNotPresent
  # -- Docker image tag
  tag: "1.3.17"
  # -- Docker image checksum
  sha256: 90f0c16cea2c5fcd8127c76d03d9eaa6e6bfa47de84a267b51467a6b3471556d

# -- Log level to use. Valid values: error/warning/info/debug
logLevel: info

# -- Configure directory-connector with environment variables.
# <https://campus.barracuda.com/product/cloudgenaccess/doc/93201555/parameters/>
customEnv: []
  # - name: FYDE_GROUPS_INCLUDED
  #   value: "Engineering"

service:
  port:
    # -- Port number to serve prometheus metrics
    metrics: 9000

# -- Recomended resources for initial deployment
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

podAnnotations: {}
nodeSelector: {}
tolerations: []
