{{- if index .Values "http-test" "enable" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cga-proxy.http-test.fullname" . }}
  labels:
    {{- include "cga-proxy.labels" . | nindent 4 }}
    {{- include "cga-proxy.http-test.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ (index .Values "http-test" "service" "port" "http" ) }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cga-proxy.selectorLabels" . | nindent 4 }}
    {{- include "cga-proxy.http-test.labels" . | nindent 4 }}
{{- end -}}
