{{- if .Values.cronjob.enabled -}}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "cga-directory-connector.fullname" . }}
  labels:
    {{- include "cga-directory-connector.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  concurrencyPolicy: Replace
  suspend: {{ .Values.cronjob.suspended | default "false" }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "cga-directory-connector.labels" . | nindent 12 }}
        spec:
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          priorityClassName: {{ .Values.priorityClassName }}
          restartPolicy: Never
          containers:
            - name: directory-connector
              {{- if .Values.image.sha }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}@sha256:{{ .Values.image.sha }}"
              {{- else }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              {{- end }}
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                {{- with .Values.customEnv }}
                  {{- toYaml . | nindent 16 }}
                {{- end }}
                - name: FYDE_ENROLLMENT_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.enrollmentToken.existingSecret.name | default (include "cga-directory-connector.fullname" .) }}
                      key: {{ .Values.enrollmentToken.existingSecret.key | default "enrollmentToken" }}
                - name: FYDE_PROMETHEUS
                  value: "true"
                - name: FYDE_PROMETHEUS_PORT
                  value: {{ .Values.service.port.metrics | quote }}
                - name: FYDE_LOGLEVEL
                  value: {{ .Values.logLevel }}
                - name: FYDE_RUN_ONCE
                  value: "true"
              ports:
                - name: metrics
                  containerPort: {{ .Values.service.port.metrics }}
                  protocol: TCP
              readinessProbe:
                initialDelaySeconds: 10
                periodSeconds: 5
                httpGet:
                  path: /
                  port: metrics
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          nodeSelector:
            {{- toYaml .Values.nodeSelector | nindent 12 }}
          tolerations:
            {{- toYaml .Values.tolerations | nindent 12 }}
{{- end }}
