{{- if or .Values.enrollmentToken.newSecret.value .Values.authToken.newSecret.value -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cga-directory-connector.fullname" . }}
  labels:
    {{- include "cga-directory-connector.labels" . | nindent 4 }}
type: Opaque
data:
  {{ if .Values.enrollmentToken.newSecret.value -}}
  enrollmentToken: {{ .Values.enrollmentToken.newSecret.value | b64enc | quote}}
  {{- end }}
  {{ if .Values.authToken.newSecret.value -}}
  authToken: {{ .Values.authToken.newSecret.value | b64enc | quote}}
  {{- end }}
{{- end }}
