{{- if and .Values.deployment.enabled .Values.serviceMonitor.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cga-directory-connector.fullname" . }}
  labels:
    {{- include "cga-directory-connector.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port.metrics }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "cga-directory-connector.selectorLabels" . | nindent 4 }}
{{- end }}
