apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cga-proxy.orchestrator.fullname" . }}
  labels:
    {{- include "cga-proxy.labels" . | nindent 4 }}
    {{- include "cga-proxy.orchestrator.labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  replicas: {{ include "cga-proxy.orchestrator.replicaCalc" . }}
  selector:
    matchLabels:
      {{- include "cga-proxy.selectorLabels" . | nindent 6 }}
      {{- include "cga-proxy.orchestrator.labels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/orchestrator/secret.yaml") . | sha256sum }}
        {{- with .Values.commonPodAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.orchestrator.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "cga-proxy.selectorLabels" . | nindent 8 }}
        {{- include "cga-proxy.orchestrator.labels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.orchestrator.podSecurityContext | nindent 8 }}
      priorityClassName: {{ .Values.priorityClassName }}
      containers:
        - name: orchestrator
          securityContext:
            {{- toYaml .Values.orchestrator.securityContext | nindent 12 }}
          image: {{ include "cga-proxy.orchestrator.imageConcat" . }}
          imagePullPolicy: {{ .Values.orchestrator.image.pullPolicy }}
          env:
            {{- with .Values.orchestrator.customEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: FYDE_GRPC_LISTENER
              value: {{ printf "[::]:%s" ( .Values.orchestrator.service.port.grpc | toString ) | quote }}
            - name: FYDE_ENROLLMENT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.orchestrator.enrollmentToken.existingSecret.name | default (include "cga-proxy.orchestrator.fullname" .) }}
                  key: {{ .Values.orchestrator.enrollmentToken.existingSecret.key | default "enrollmentToken" }}
            - name: FYDE_PROXY_PROMETHEUS
              value: {{ .Values.serviceMonitor | quote }}
            - name: FYDE_ENVOY_PROMETHEUS
              value: {{ .Values.serviceMonitor | quote }}
            # Envoy reads the configuration from the orchestrator
            - name: FYDE_ENVOY_LISTENER_PORT
              value: {{ .Values.envoy.service.port.listener | quote }}
            {{- if .Values.orchestrator.highAvailability.enabled }}
            - name: FYDE_REDIS_SENTINEL_HOSTS
              value: {{ printf "%s-%s:%d" .Release.Name (index .Values "redis-ha" "nameOverride") (index .Values "redis-ha" "sentinel" "port" | int) }}
            - name: FYDE_REDIS_SENTINEL_SERVICE_NAME
              value: {{ index .Values "redis-ha" "redis" "masterGroupName" }}
            {{- end }}
          ports:
            - name: grpc
              containerPort: {{ .Values.orchestrator.service.port.grpc }}
              protocol: TCP
            {{- if .Values.serviceMonitor }}
            - name: metrics
              containerPort: {{ .Values.orchestrator.service.port.metrics }}
              protocol: TCP
            {{- end }}
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            tcpSocket:
              port: grpc
          resources:
            {{- toYaml .Values.orchestrator.resources | nindent 12 }}
      nodeSelector:
        {{- toYaml .Values.orchestrator.nodeSelector | nindent 8 }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                {{- include "cga-proxy.orchestrator.labels" . | nindent 16 }}
            topologyKey: kubernetes.io/hostname
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "cga-proxy.orchestrator.labels" . | nindent 20 }}
                topologyKey: failure-domain.beta.kubernetes.io/zone
      tolerations:
        {{- toYaml .Values.orchestrator.tolerations | nindent 8 }}
