{{- if gt (include "cga-proxy.orchestrator.replicaCalc" . | int) 1 -}}
---
{{ if $.Capabilities.APIVersions.Has "policy/v1/PodDisruptionBudget" -}}
apiVersion: policy/v1
{{- else -}}
apiVersion: policy/v1beta1
{{- end }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "cga-proxy.orchestrator.fullname" . }}
  labels:
    {{- include "cga-proxy.labels" . | nindent 4 }}
    {{- include "cga-proxy.orchestrator.labels" . | nindent 4 }}
spec:
  minAvailable: {{ div (mul (include "cga-proxy.orchestrator.replicaCalc" .) 2) 3 }}
  selector:
    matchLabels:
      {{- include "cga-proxy.selectorLabels" . | nindent 6 }}
      {{- include "cga-proxy.orchestrator.labels" . | nindent 6 }}
{{- end -}}
