{{- if .Values.orchestrator.enrollmentToken.newSecret.value -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cga-proxy.orchestrator.fullname" . }}
  labels:
    {{- include "cga-proxy.labels" . | nindent 4 }}
    {{- include "cga-proxy.orchestrator.labels" . | nindent 4 }}
type: Opaque
stringData:
  enrollmentToken: "{{ .Values.orchestrator.enrollmentToken.newSecret.value }}"
{{- end }}
