name: Docs check

on: pull_request

jobs:
  docs-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Ensure documentation is updated
        run: make helm-docs git-clean
